{{- if .Values.webhook.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{- .Values.webhook.name -}}
spec:
  selector:
    app: {{- .Values.webhook.name -}}
  ports:
    - name: http
      port: 443
      targetPort: 8443
{{- end }}