{{- if .Values.webhook.enabled }}
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ .Values.webhook.name }}
webhooks:
  - name: {{ .Values.webhook.name }}.{{ .Release.Namespace }}.svc
    clientConfig:
      service:
        name: {{ .Values.webhook.name }}
        namespace: {{ .Release.Namespace }}
        port: 443
        path: "/validate"
      caBundle: {{ required "please rerun helm install" .Values.webhook.caBundle }}
    rules:
      - operations:
          - "CREATE"
          - "UPDATE"
        apiGroups:
          - {{ .Values.crds.group }}
        apiVersions:
          - {{ .Values.crds.version }}
        resources:
          - "configurations"
        scope: "*"
    admissionReviewVersions:
      - v1
    sideEffects: None
{{- end }}