{{- if .Values.rbac.enabled }}
apiVersion: v1
kind: List
items:
- apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: {{ .Values.webhook.name }}
    namespace: {{ .Release.Namespace }}
- apiVersion: rbac.authorization.k8s.io/v1
  kind: Role
  metadata:
    name: {{ .Values.webhook.name }}
    namespace: {{ .Release.Namespace }}
  rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
- apiVersion: rbac.authorization.k8s.io/v1
  kind: RoleBinding
  metadata:
    name: {{ .Values.webhook.name }}
    namespace: {{ .Release.Namespace }}
  roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: {{ .Values.webhook.name }}
  subjects:
  - kind: ServiceAccount
    name: {{ .Values.webhook.name }}
    namespace: {{ .Release.Namespace }}
{{- end }}
